version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Colombo

    open-pull-requests-limit: 5

    labels:
      - dependencies
      - python

    commit-message:
      prefix: "deps"
      include: scope

    groups:
      python-production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch

      python-development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Asia/Colombo

    open-pull-requests-limit: 5

    labels:
      - dependencies
      - github-actions

    commit-message:
      prefix: "ci"
      include: scope

    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch